### ISSUE TITLE
Container height does not change if content height inside has changed

### ISSUE THREAD

**Issue by cve** [danieldiekmeier/vue-slide-up-down#8]
Hi,

I have a form inside that component and when the form get's invalid state then it expands a little, but container from vue-slide-up-down does not reflect that change, I have no idea for now how to implement it.

**Comment by danieldiekmeier** [comment]
Try calling the SlideUpDown component's `layout()` method after your form errors are rendered. I don't know which (if any) validation library you use, but if it provides a callback, you could try setting up some kind of event emitter/watcher, or similar messaging.

Because the actual component (https://github.com/danieldiekmeier/vue-slide-up-down/blob/master/src/slide-up-down.js) is so small, I'd advise you to just copy it into your project to make the relevant changes.
