### ISSUE TITLE
Active by default not working in Modal/Portlet or other hidden elements

### ISSUE THREAD

**Issue by ridaamirini** [danieldiekmeier/vue-slide-up-down#9]
Hello togther,

if the parent element is hidden, but the component is active we get a scrollHeight of 0. So if we open the modal the element is not visible because of the wrong height. I think we need to resize when the parent is visibility changes.

**Comment by danieldiekmeier** [comment]
I‘m afraid that would be out of scope for this package, because it would involve (if we wanted to do it right) tracking at least the complete chain of parents, or maybe even the whole DOM.

If you want to use this component, I‘d advise you to copy the source code (it‘s quite short) into your project and make any necessary changes for your use case there.
